### ISSUE TITLE
Choose non-Ubuntu base image?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli-docker#13]
http://mjg59.dreamwidth.org/36312.html 

This post + some common practice I've been seeing + some discussions on twitter makes me think if we still should go with Ubuntu base image or switch to something like Debian which is probably nearly identical.

We can apt-get install if there are  the missing packages  and rely on `debian` base image which is more frequently maintained and commonly used by others.

**Comment by devigned** [comment]
I think switching to Debian sounds like the best path.

**Comment by devigned** [comment]
Fixed in #14
