### ISSUE TITLE
0.9.19 is not tagged on Docker hub

### ISSUE THREAD

**Issue by colemickens** [Azure/azure-cli-docker#30]

**Comment by colemickens** [comment]
Bump. I'd like to use this on all of my machines without having to manually clone the repo and build this myself.

cc: @devigned

**Comment by devigned** [comment]
We'll get this sorted out tomorrow. Thank you for the kind reminder.

**Comment by devigned** [comment]
@eduardkoller and @mayurid let's chat through this tomorrow.

**Comment by amarzavery** [comment]
I remember updating latest to 0.9.19
![image](https://cloud.githubusercontent.com/assets/4521223/14608804/03a6869c-053c-11e6-877c-20371a85cbf8.png)

**Comment by amarzavery** [comment]
Yes, you are right, 14 days ago when build with latest tag was run, it had 0.9.14 linked to it.
FROM debian:jessie

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

ENV AZURE_CLI_VERSION "0.9.14"
ENV NODEJS_APT_ROOT "node_4.x"
ENV NODEJS_VERSION "4.2.4"

May be I messed up something. Will fix this ASAP.

**Comment by amarzavery** [comment]
@colemickens 
The build with latest tag to 0.9.19 is now successful.

Relevant info from the build logs:

FROM debian:jessie

RUN rm /bin/sh && ln -s /bin/bash /bin/sh

ENV AZURE_CLI_VERSION "0.9.19"
ENV NODEJS_APT_ROOT "node_4.x"
ENV NODEJS_VERSION "4.2.4"



info:             _    _____   _ ___ ___
info:            /_\  |_  / | | | _ \ __|
info:      _ ___/ _ \__/ /| |_| |   / _|___ _ _
info:    (___  /_/ \_\/___|\___/|_|_\___| _____)
info:       (_______ _ _)         _ ______ _)_ _ 
info:              (______________ _ )   (___ _ _)
info:    
info:    Microsoft Azure: Microsoft's Cloud Platform
info:    
info:    Tool version 0.9.19

**Comment by colemickens** [comment]
Thank you @amarzavery!
