### ISSUE TITLE
Cannot install cli 0.10.17 using docker

### ISSUE THREAD

**Issue by mabicca** [Azure/azure-cli-docker#50]
It seems that we had these commands to run cli1 or cli2:
docker run -it microsoft/azure-cli:latest
docker run -it azuresdk/azure-cli-python:latest

In the past the first command would install the latest 1.x version of the azure cli whereas the second command installs the latest version of the 2.x az cli.

At the moment, both commands will install cli version 2.0.25, so there is no current way to install 0.10.17.

Even when specifying that version you get an error:
docker run -it microsoft/azure-cli:0.10.17
Unable to find image 'microsoft/azure-cli:0.10.17' locally
docker: Error response from daemon: manifest for microsoft/azure-cli:0.10.17 not found.
See 'docker run --help'.

If you specify 0.10.14, it does work properly:
docker run -it microsoft/azure-cli:0.10.14
root@44e708604127:/#

**Comment by mabicca** [comment]
We also know 1.x has been deprecated, but there are still a few cases that we are troubleshooting where compatible parameters are not yet implemented in cli 2.x (mostly around encryption). 

Should we assume the latest version we can use from cli 1.x is 0.10.14? Just asking that since I am not sure this is indeed a bug or expected behavior.

**Comment by kevhill** [comment]
second this issue. I need to create and destroy HDinsight clusters from a Linux laptop, and because of this bug there is no way to do that.

**Comment by kevhill** [comment]
OK! I think I have it.

They were trying to get the node.deb from here: https://deb.nodesource.com/node_6.x/pool/main/n/nodejs/

But version 6.11.3 wasn't maintained there. 6.11.2 was, so I've modified my Dockerfile to use 6.11.2, and then rebuilt the Dockerfile. It looks like it worked!

```
root@349491f45d20:/# azure --version
0.10.17 (node: 6.11.2)
```

I have to run right now, but I'll try and put up a pr in a bit....
