### ISSUE TITLE
Install some other dev tools

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-cli-docker#6]
Since this package is for experimentation/development, it probably should include some common tools. Currently base Docker image is `ubuntu`, it doesn't have much stuff installed in it (like a standard Ubuntu distribution).

My suggestions:

* `curl`/`wget` (http client)
* `git` (cvs)
*  `openssl` (certs management –can be used for generating certs in service management APIs)
* `jq` (json data manipulation/formatting)

Having those in the image will save users time with a only little bigger image size (~50mb).

Any other ideas?

**Comment by devigned** [comment]
Fixed in #14
